### ISSUE TITLE
'Cannot assign requested address' on connect

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ashish21590/redis#178]
```
I'm using predis and from time to time I have these messages in php.err:

PHP Fatal error:  Uncaught exception 'Predis_ClientException' with message
'Cannot assign requested address' in /home/meshok/predis.php:648
Stack trace:
#0 /home/meshok/predis.php(708): Predis_Connection->connect()
#1 /home/meshok/predis.php(680): Predis_Connection->getSocket()
#2 /home/meshok/predis.php(116):
Predis_Connection->writeCommand(Object(Predis_Commands_SetAdd))
#3 /home/meshok/predis.php(124):
Predis_Client->executeCommandInternal(Object(Predis_Connection),
Object(Predis_Commands_SetAdd))
#4 /home/meshok/predis.php(108):
Predis_Client->executeCommand(Object(Predis_Commands_SetAdd))
#5 [internal function]: Predis_Client->__call('sadd', Array)
#6 /home/meshok/bounce.php(55): Predis_Client->sadd('emails_550',
'storm@radioener...')


What version of the product are you using? On what operating system?
redis 1.2.2 32 bit on 64 bit debian

What can couse that

```

Original issue reported on code.google.com by `alexc...@gmail.com` on 10 Mar 2010 at 6:51

**Comment by GoogleCodeExporter** [comment]
```
solved. Not a redis problem.
```

Original comment by `alexc...@gmail.com` on 13 Mar 2010 at 10:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `anti...@gmail.com` on 24 Aug 2010 at 3:18
- Changed state: **Invalid**
