### ISSUE TITLE
Errno::EAGAIN: Resource temporarily unavailable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ashish21590/redis#38]
```

Using a constant batch and a website polling on the content gives this:



/lib/redis.rb:437:in `get_response': #<Errno::EAGAIN: Resource temporarily
unavailable> (RedisError)
    from ./lib/redis.rb:192:in `get'
    from ./lib/redis.rb:187:in `[]'

I'm on a Virtual Machine but dowsn't seem to be a memory problem:

             total       used       free     shared    buffers     cached
Mem:        786432     123196     663236          0          0          0
-/+ buffers/cache:     123196     663236
Swap:            0          0          0



```

Original issue reported on code.google.com by `drew...@gmail.com` on 19 May 2009 at 8:26

**Comment by GoogleCodeExporter** [comment]
```
Hello!

This is a timeout problem, just update to the latest redis-rb ruby client and 
the 
problem should disappear. In the new versions of the client you can set the 
timeout 
to a new value. Also it may be a problem with reconnection. This should be 
fixed 
now too.

Grab the latest ruby client from:

http://github.com/ezmobius/redis-rb/tree/master
```

Original comment by `anti...@gmail.com` on 19 May 2009 at 9:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `anti...@gmail.com` on 22 May 2009 at 4:45
- Changed state: **Fixed**
